name: Build Extension

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compress extension folder
      run: cd extension/WebMimic ; zip -r WebMimic.zip *

    - name: Gets latest created release info
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.2.1
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: WebMimic.zip

    - name: Publish to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
        asset_path: WebMimic.zip
        asset_name: WebMimic.zip
        asset_content_type: application/zip
