name: Publish WebMimic Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compress extension folder
      run: zip -r WebMimic.zip /extensions/WebMimic/*

    - name: Publish to release
      uses: actions/upload-release-asset@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        name: WebMimic.zip
        file: WebMimic.zip
