name: Zip and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip folder
      run: zip -r WebMimic.zip extension/WebMimic

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: 'latest'
        asset_path: WebMimic.zip
        asset_name: WebMimic.zip
        asset_content_type: application/zip
